fields_and_plus_codes = {
    "Antioch HS": "2CW2+P7 Antioch, Nashville, TN",
    "Beech HS": "99CH+WM Hendersonville, Tennessee",
    # "Brentwood Academy": "25MH+47 Brentwood, Tennessee", # baseball field,
    "Brentwood Academy": "25MJ+F8 Brentwood, Tennessee",
    "Cane Ridge HS": "29JH+69 Nashville, Tennessee",
    "Centennial HS": "W5JH+32 Franklin, Tennessee",
    "Davidson Academy": "76JC+CQ Nashville, Tennessee",
    "Drakes Creek": "896Q+6C Hendersonville, Tennessee",
    "East Nashville Magnet HS": "56HX+VH Nashville, Tennessee",
    "Ezell Harding Academy": "3977+VV Antioch, Nashville, TN",
    "First Horizon Park": "56F7+8W Nashville, Tennessee",
    # "Franklin HS": "W4VF+9M Franklin, Tennessee", # Cheeks Park
    "Franklin HS": "W4QC+MP Franklin, Tennessee",
    "Glencliff HS": "472F+H5 Nashville, Tennessee",
    "Harpeth HS": "3WQ4+RC Kingston Springs, Tennessee",
    "Hillsboro HS": "454Q+R2 Nashville, Tennessee",
    "Hume Fogg Magnet HS": "45VV+92 Nashville, Tennessee",
    "Hunters Lane HS": "76HW+HP Nashville, Tennessee",
    "Independence HS": "R4F5+RG Thompson's Station, Tennessee",
    "John Overton HS": "36HH+VW Nashville, Tennessee",
    "Lipscomb Academy": "4643+JF Nashville, Tennessee",
    "Lipscomb University": "4622+XF Nashville, Tennessee",
    "Maplewood HS": "67J2+V4 Nashville, Tennessee",
    "McCabe Park": "45R4+MQ Nashville, Tennessee",
    "McGavock HS": "58PC+7Q Nashville, Tennessee",
    "Middle TN Christian School": "VJ98+MC Murfreesboro, Tennessee",
    "MLK Jr Magnet HS": "556X+MQ Nashville, Tennessee",
    # "Oakland HS": "VJMX+R9 Murfreesboro, Tennessee", # baseball field
    "Oakland HS": "VJJX+V7 Murfreesboro, Tennessee",
    "Page HS": "R6XW+63 Franklin, Tennessee",
    "Pope John Paul II HS": "888H+9X Hendersonville, Tennessee",
    "Ravenwood HS": "X63P+X8 Brentwood, Tennessee",
    "Riverdale HS": "RH8R+4J Murfreesboro, Tennessee",
    # "Rose Park": "46V9+73 Nashville, Tennessee", # baseball field
    "Rose Park": "46V8+9P Nashville, Tennessee",
    # "Rotary Park, Donelson": "695F+GM Old Hickory, Nashville, TN", # baseball field
    "Rotary Park, Donelson": "694G+XQ Old Hickory, Nashville, TN",
    "Shelby Park": "5788+HR Nashville, Tennessee",
    "Siegel HS": "WJ62+7W Murfreesboro, Tennessee",
    "Station Camp HS": "9F63+JJ Gallatin, Tennessee",
    "Stratford STEM Magnet": "57WJ+XH Nashville, Tennessee",
    "Summit HS": "Q4CG+R5 Spring Hill, Tennessee",
    "Vanderbilt University": "45VV+92 Nashville, Tennessee",
    "Whites Creek HS": "75GJ+M9 Whites Creek, Nashville, TN",
}
